# Generated by Django 4.2.9 on 2024-06-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reponse',
        ),
    ]
