# Generated by Django 4.2.9 on 2024-06-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_reponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='auteur',
            field=models.CharField(max_length=34),
        ),
    ]
