# Generated by Django 4.2.9 on 2024-06-04 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_reponse_auteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.reponse')),
            ],
        ),
    ]
