# Generated by Django 4.2.9 on 2024-06-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikes',
            name='reponse',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='likes',
            name='reponse',
            field=models.TextField(max_length=300),
        ),
    ]
