# Generated by Django 4.2.9 on 2024-06-05 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_dislikes_reponse_alter_likes_reponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='reponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.reponse'),
        ),
    ]
