# Generated by Django 4.2.9 on 2024-06-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_likes_reponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
