# Generated by Django 4.2.9 on 2024-06-05 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_likes_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dislikes',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dislikes',
            name='reponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.reponse'),
        ),
    ]
