# Generated by Django 4.2.9 on 2024-06-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_dislikes_quantity_alter_dislikes_reponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='quantity',
        ),
    ]
