# Generated by Django 4.2.9 on 2024-06-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_likes_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislikes',
            old_name='quantity',
            new_name='count',
        ),
    ]
