# Generated by Django 4.2.9 on 2024-06-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_quantity_dislikes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikes',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='likes',
            name='count',
            field=models.IntegerField(),
        ),
    ]
