# Generated by Django 4.2.9 on 2024-06-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_dislikes_count_alter_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dislikes',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='likes',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
