# Generated by Django 4.2.9 on 2024-06-11 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_dislikes_count_alter_likes_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dislikes',
        ),
    ]
