# Generated by Django 4.2.9 on 2024-06-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_delete_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
