# Generated by Django 4.2.9 on 2024-06-11 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_likes_is_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='count',
        ),
    ]
