# Generated by Django 4.2.9 on 2024-06-11 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_likes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.reponse')),
            ],
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
