# Generated by Django 4.2.9 on 2024-07-19 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='reponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='base.reponse'),
        ),
    ]
